spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ele?allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      web-stat-filter:
        enabled: false
        url-pattern: /1.0/*
      stat-view-servlet:
        enabled: false
        login-username: mask
        login-password: hydee_mask
        url-pattern: /druid/*
  profiles:
    active: local
server:
  port: 8888
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # Âß¼­É¾³ýÅäÖÃ
    db-config:
      # É¾³ýÇ°
      logic-not-delete-value: 1
      # É¾³ýºó
      logic-delete-value: 0